import type { Metadata } from "next";
import CssBaseline from "@mui/material/CssBaseline";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderAppBar from "@/components/HeaderAppBar";
import Footer from "@/components/Footer";
import Container from "@mui/material/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memo App",
  description: "Generated by create next app and Contentful and MUI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <CssBaseline />
          <HeaderAppBar />
          <Container maxWidth="lg">{children}</Container>
          <Footer
            title="Footer"
            description="Something here to give the footer a purpose!"
          />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
